### PR TITLE
add chip model ID output

### PR DESCRIPTION
**Pull request by shawaj**
add chip model ID output to enable easier determination between sx1302 and sx1303

### CODE REVIEW

**Comment by shawaj** [comment]
example output...
```
root@f986d0ed3f2c:/opt/iotloragateway/packet_forwarder# sx1302/util_chip_id/chip_id -d /dev/spidev1.2
CoreCell reset through GPIO22...
Opening SPI communication interface
Note: chip version is 0x12 (v1.2)
INFO: using legacy timestamp
ARB: dual demodulation disabled for all SF

INFO: concentrator chip model ID: 0x03

INFO: concentrator EUI: 0x0016c001ff1e8374

Closing SPI communication interface
CoreCell reset through GPIO22...
```

**Comment by joelguittet** [comment]
@shawaj I suggest to have it in the chip_id utility as well (file "util_chip_id/src/chip_id.c").

**Comment by shawaj** [comment]
> @shawaj I suggest to have it in the chip_id utility as well (file "util_chip_id/src/chip_id.c").

That's where it is currently @joelguittet - did you mean somewhere else?

**Comment by joelguittet** [comment]
@shawaj sorry I'm a little bit tired. I was thinking to "packet_forwarder/src/lora_pkt_fwd.c" instead. EUI is printed as well but not the model ID.

**Comment by shawaj** [comment]
> @shawaj sorry I'm a little bit tired. I was thinking to "packet_forwarder/src/lora_pkt_fwd.c" instead. EUI is printed as well but not the model ID.

Aha yes I see where you mean now!

**Pull request closed without merging**
